# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CqCMK1FBcAIkHP4VftaD2WdaJOQpCQbI
"""

import streamlit as st
import pandas as pd
import random
from fpdf import FPDF
from datetime import datetime, timedelta
import io

# ==========================================
#   1. APP CONFIGURATION & STYLING
# ==========================================
st.set_page_config(
    page_title="Dental Roster Pro",
    page_icon="🦷",
    layout="wide",
    initial_sidebar_state="auto"
)

# Custom CSS for Mobile & Desktop
st.markdown("""
    <style>
    .block-container { padding-top: 1rem; padding-bottom: 5rem; }
    h1 { font-size: 1.8rem; color: #2c3e50; }
    .stButton>button {
        height: 3.5em;
        border-radius: 10px;
        width: 100%;
        font-weight: bold;
        background-color: #ff4b4b;
        color: white;
    }
    .metric-box {
        background-color: #f0f2f6;
        padding: 10px;
        border-radius: 8px;
        text-align: center;
        font-weight: bold;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
#   2. HELPER FUNCTIONS
# ==========================================

def get_empty_template():
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        pd.DataFrame(columns=[
            "Name", "Title", "Shift_Pref", "Supervisor", "Target_Load",
            "Sun_Activity", "Vacation_Start", "Vacation_End"
        ]).to_excel(writer, sheet_name="Doctors", index=False)
        pd.DataFrame(columns=["Clinic_Number"]).to_excel(writer, sheet_name="Clinics", index=False)
    return buffer

def generate_dates(start_date, end_date):
    date_list = []
    current = start_date
    while current <= end_date:
        if current.strftime("%A") not in ["Friday", "Saturday"]:
            date_list.append(current)
        current += timedelta(days=1)
    return date_list

def is_on_vacation(doc, current_day_name):
    DAY_INDEX = {"Sunday": 0, "Monday": 1, "Tuesday": 2, "Wednesday": 3, "Thursday": 4}
    v_start = doc.get("Vacation_Start")
    v_end = doc.get("Vacation_End")
    if pd.isna(v_start) or pd.isna(v_end) or v_start is None: return False

    start_idx = DAY_INDEX.get(v_start, -1)
    end_idx = DAY_INDEX.get(v_end, -1)
    curr_idx = DAY_INDEX.get(current_day_name, -1)

    if start_idx != -1 and start_idx <= curr_idx <= end_idx: return True
    return False

def create_pdf(df, start_str, end_str, clinics):
    pivot_df = df.pivot(index=['SortDate', 'Day', 'Shift'], columns='Clinic', values='Doctor')

    # Sort Columns
    cols = [str(c) for c in clinics]
    # Add special columns in specific order
    for e in ["Sci. Day (2 Sess)", "Floor/Reserve", "VACATION"]:
        if e in pivot_df.columns: cols.append(e)
    final_cols = [c for c in cols if c in pivot_df.columns]

    pivot_df = pivot_df[final_cols].fillna("-")

    # PDF Config
    pdf = FPDF(orientation='L', unit='mm', format='A4')
    pdf.add_page()
    pdf.set_font("Arial", size=8)

    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Dental Schedule: {start_str} to {end_str}", ln=True, align='C')
    pdf.ln(5)

    # Table Header
    w_day, w_shift, w_clinic = 35, 15, 35
    pdf.set_fill_color(52, 73, 94) # Dark Blue
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", 'B', 9)

    pdf.cell(w_day, 10, "Date", 1, 0, 'C', 1)
    pdf.cell(w_shift, 10, "Shift", 1, 0, 'C', 1)
    for col in final_cols:
        # Dynamic width adjustment for long headers
        curr_w = 40 if "Sci" in col else w_clinic
        pdf.cell(curr_w, 10, col, 1, 0, 'C', 1)
    pdf.ln()

    # Table Body
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=7)
    pivot_df = pivot_df.reset_index().sort_values(['SortDate', 'Shift'])

    for _, row in pivot_df.iterrows():
        cell_height = 10
        day_text = str(row['Day']).replace("\n", " - ")

        pdf.cell(w_day, cell_height, day_text, 1, 0, 'C')

        # Shift Color
        if row['Shift'] == "PM":
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(w_shift, cell_height, row['Shift'], 1, 0, 'C', 1)
        else:
            pdf.cell(w_shift, cell_height, row['Shift'], 1, 0, 'C')

        # Clinic Cells
        for col in final_cols:
            text = str(row[col])
            curr_w = 40 if "Sci" in col else w_clinic

            if "OFF" in text or col == "VACATION":
                 pdf.set_text_color(150, 150, 150)
                 pdf.cell(curr_w, cell_height, text, 1, 0, 'C')
                 pdf.set_text_color(0, 0, 0)
            elif "(Sup)" in text:
                pdf.set_font("Arial", 'B', 7)
                pdf.cell(curr_w, cell_height, text, 1, 0, 'C')
                pdf.set_font("Arial", '', 7)
            else:
                pdf.cell(curr_w, cell_height, text, 1, 0, 'C')
        pdf.ln()

    output_pdf = "temp_schedule.pdf"
    pdf.output(output_pdf)
    return output_pdf

# ==========================================
#   3. SIDEBAR
# ==========================================
with st.sidebar:
    st.title("⚙️ Setup")
    uploaded_file = st.file_uploader("Upload Excel", type=["xlsx"])

    if not uploaded_file:
        st.markdown("---")
        st.download_button("📄 Get Template", get_empty_template(), "dental_template.xlsx")

    st.markdown("---")
    st.markdown("**Select Week:**")
    start_d = st.date_input("Start", datetime.today())
    end_d = st.date_input("End", datetime.today() + timedelta(days=4))

# ==========================================
#   4. MAIN DASHBOARD
# ==========================================
st.title("🦷 Dental Roster Pro")

# --- LOAD DATA ---
if uploaded_file:
    try:
        df_docs = pd.read_excel(uploaded_file, sheet_name="Doctors")
        df_clinics = pd.read_excel(uploaded_file, sheet_name="Clinics")
    except:
        st.error("Error reading Excel. Please use the template.")
        st.stop()
else:
    # Default Demo Data
    df_docs = pd.DataFrame([
        {"Name": "Dr. Amjad", "Title": "Res", "Shift_Pref": "Both", "Supervisor": False, "Target_Load": 5, "Sun_Activity": False, "Vacation_Start": None, "Vacation_End": None},
        {"Name": "Dr. Shady", "Title": "Cons", "Shift_Pref": "Day", "Supervisor": True, "Target_Load": 2, "Sun_Activity": True, "Vacation_Start": None, "Vacation_End": None}
    ])
    df_clinics = pd.DataFrame([{"Clinic_Number": 15}, {"Clinic_Number": 10}, {"Clinic_Number": 9}, {"Clinic_Number": 8}])

# --- STATS ---
c1, c2, c3 = st.columns(3)
c1.markdown(f"<div class='metric-box'>Doctors: {len(df_docs)}</div>", unsafe_allow_html=True)
c2.markdown(f"<div class='metric-box'>Clinics: {len(df_clinics)}</div>", unsafe_allow_html=True)
c3.markdown(f"<div class='metric-box'>Residents: {len(df_docs[df_docs['Title'].str.contains('Res', case=False, na=False)])}</div>", unsafe_allow_html=True)

st.markdown("---")

# --- TABS ---
tab1, tab2, tab3 = st.tabs(["👥 Team List", "🏥 Clinic Units", "🚀 Schedule"])

with tab1:
    st.info("ℹ️ **Note:** All Residents ('Res') are automatically assigned to Scientific Day on Sunday AM.")
    edited_docs_df = st.data_editor(
        df_docs, num_rows="dynamic", use_container_width=True,
        column_config={
            "Supervisor": st.column_config.CheckboxColumn("Sup?", width="small"),
            "Sun_Activity": st.column_config.CheckboxColumn("Sun (Opt)", width="small", help="For Non-Residents who want to attend"),
            "Shift_Pref": st.column_config.SelectboxColumn("Pref", options=["Day", "Night", "Both"], width="medium"),
        }
    )

with tab2:
    edited_clinics_df = st.data_editor(df_clinics, num_rows="dynamic", use_container_width=True)

with tab3:
    if st.button("Generate Schedule Now"):
        # 1. PREPARE DATA
        doctors_db = edited_docs_df.to_dict('records')
        clinic_list = edited_clinics_df["Clinic_Number"].tolist()
        workload_tracker = {doc['Name']: 0 for doc in doctors_db}
        schedule_rows = []

        # 2. ASSIGN WEEKLY TEAMS
        day_team, night_team, flexible = [], [], []
        for doc in doctors_db:
            pref = doc.get("Shift_Pref", "Both")
            if pref == "Day": day_team.append(doc)
            elif pref == "Night": night_team.append(doc)
            else: flexible.append(doc)

        # Balance teams
        random.shuffle(flexible)
        for doc in flexible:
            if len(day_team) <= len(night_team): day_team.append(doc)
            else: night_team.append(doc)

        # 3. GENERATE SHIFTS
        dates = generate_dates(start_d, end_d)

        for d in dates:
            day_name = d.strftime("%A")
            date_str = d.strftime("%Y-%m-%d")
            display_date = f"{day_name}\n{date_str}"

            def process_shift(team, shift_label):
                available = []
                for doc in team:
                    if is_on_vacation(doc, day_name):
                        schedule_rows.append({"Day": display_date, "SortDate": date_str, "Shift": shift_label, "Clinic": "VACATION", "Doctor": f"{doc['Name']} (OFF)"})
                    else: available.append(doc)

                # Sort: Random shuffle + Workload priority
                random.shuffle(available)
                available.sort(key=lambda x: workload_tracker[x['Name']])

                assigned_count = 0
                for doc in available:
                    # --- SCIENTIFIC DAY LOGIC ---
                    # 1. Is it Sunday AM?
                    # 2. Is Doctor a Resident? OR Did they check the box?
                    is_res = "Res" in str(doc.get("Title", "")) # Check if Title contains "Res"
                    user_opt_in = doc.get("Sun_Activity") == True

                    if shift_label == "AM" and day_name == "Sunday" and (is_res or user_opt_in):
                        loc = "Sci. Day (2 Sess)"
                    else:
                        if assigned_count < len(clinic_list):
                            loc = str(clinic_list[assigned_count])
                            assigned_count += 1
                            workload_tracker[doc['Name']] += 1
                        else:
                            loc = "Floor/Reserve"
                            workload_tracker[doc['